services:
  crawler:
    build: .
    container_name: amz-sif-crawler
    ports:
      - "8000:8000"
    environment:
      - DOCKER_ENV=1
      - PORT=8000
      - CORS_ALLOW_ORIGINS=*
    volumes:
      - ./runtime_data:/app/runtime_data
      - ./config:/app/config
    restart: unless-stopped
