apiVersion: v1
kind: ConfigMap
metadata:
  name: amz-sif-crawler-config
  namespace: amz-sif-crawler
data:
  DOCKER_ENV: "1"
  PYTHONUNBUFFERED: "1"
  GATEWAY_MODE: "parallel"
  AMZ_WORKER_URL: "http://amazon-worker:8000"
  SIF_WORKER_URL: "http://sif-worker:8000"
