apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amz-sif-crawler
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc-example.yaml
  - amazon-worker-deployment.yaml
  - sif-worker-deployment.yaml
  - gateway-deployment.yaml
  - services.yaml
