apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amazon-profile-pvc
  namespace: amz-sif-crawler
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sif-profile-pvc
  namespace: amz-sif-crawler
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amazon-cache-pvc
  namespace: amz-sif-crawler
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sif-cache-pvc
  namespace: amz-sif-crawler
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
