apiVersion: v1
kind: Service
metadata:
  name: amazon-worker
  namespace: amz-sif-crawler
spec:
  selector:
    app: amazon-worker
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sif-worker
  namespace: amz-sif-crawler
spec:
  selector:
    app: sif-worker
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-gateway
  namespace: amz-sif-crawler
spec:
  type: LoadBalancer
  selector:
    app: mcp-gateway
  ports:
    - name: http
      port: 8888
      targetPort: 8888
